
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class manage_movie_frame extends javax.swing.JFrame {

    /**
     * Creates new form manage_movie_frame
     */
    public manage_movie_frame() {
        initComponents();
        Dimension d= Toolkit.getDefaultToolkit().getScreenSize();
        setSize(d.getSize());
        getContentPane().setBackground(Color.WHITE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        tf1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        lb9 = new javax.swing.JLabel();
        lb10 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setText("ADD MOVIE HERE");
        getContentPane().add(lb1);
        lb1.setBounds(110, 10, 150, 16);

        lb2.setText("CATEGORY");
        getContentPane().add(lb2);
        lb2.setBounds(40, 60, 100, 16);

        lb3.setText("MOVIE");
        getContentPane().add(lb3);
        lb3.setBounds(40, 110, 36, 16);

        lb4.setText("DESCRIPTION");
        getContentPane().add(lb4);
        lb4.setBounds(40, 160, 72, 16);

        lb5.setText("SQUARE PHOTO");
        getContentPane().add(lb5);
        lb5.setBounds(40, 220, 87, 16);

        lb6.setText("WIDE PHOTO");
        getContentPane().add(lb6);
        lb6.setBounds(40, 270, 71, 16);

        lb7.setText("VIDEO");
        getContentPane().add(lb7);
        lb7.setBounds(40, 330, 33, 16);

        lb8.setText("AMOUNT");
        getContentPane().add(lb8);
        lb8.setBounds(40, 390, 51, 16);

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cb);
        cb.setBounds(170, 60, 200, 22);

        tf1.setText("jTextField1");
        getContentPane().add(tf1);
        tf1.setBounds(170, 110, 200, 22);

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 140, 230, 60);

        lb9.setText("jLabel9");
        getContentPane().add(lb9);
        lb9.setBounds(170, 216, 210, 30);

        lb10.setText("jLabel10");
        getContentPane().add(lb10);
        lb10.setBounds(170, 270, 43, 16);

        lb11.setText("jLabel11");
        getContentPane().add(lb11);
        lb11.setBounds(170, 330, 43, 16);

        tf2.setText("jTextField2");
        getContentPane().add(tf2);
        tf2.setBounds(170, 390, 220, 22);

        bt1.setText("Browse");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(30, 240, 72, 22);

        bt2.setText("Browse");
        getContentPane().add(bt2);
        bt2.setBounds(30, 290, 72, 22);

        bt3.setText("Browse");
        getContentPane().add(bt3);
        bt3.setBounds(30, 360, 72, 22);

        bt4.setText("ADD MOVIE");
        getContentPane().add(bt4);
        bt4.setBounds(150, 450, 210, 22);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(7, 60, 30, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_movie_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_movie_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_movie_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_movie_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_movie_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
